version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ..
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant_network

  second_node:
    image: vitreus_power_plant
    container_name: power-plant-second-node
    depends_on:
      - vitreus_power_plant
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/charlie
      --chain local
      --port 30333
      --rpc-port 9944
      --unsafe-rpc-external
      --prometheus-external
      --bootnodes /ip4/140.82.46.161/tcp/30333/p2p/12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      --rpc-cors all
      --telemetry-url "wss://telemetry-power-plant-dev.compliq.io:8001/submit/ 0"


    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9933:9933/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
