[package]
name = "energy-generation-rpc"
version = "0.2.0"
authors.workspace = true
edition.workspace = true

[dependencies]
energy-generation-runtime-api = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros", "client"] }
parity-scale-codec = { workspace = true }
sp-api = { workspace = true, default-features = false }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true, default-features = false }
