[package]
name = "vitreus-utility-runtime-api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
sp-api = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "sp-core/std",
]
