image: rust:1.70
clone:
  depth: full 

pipelines:
  branches:   
    develop:
      # - step:
          # name: Build and Run Tests
          # script:
          #   - rustup target add wasm32-unknown-unknown
          #   - export RUSTFLAGS="-C strip=debuginfo"
          #   - apt-get update && apt-get install -y cmake build-essential clang libclang-dev protobuf-compiler pkg-config libssl-dev libpq-dev gcc llvm jq 
          #   - cargo fmt -- --check
          #   - cargo clippy -- -D warnings
          #   - cargo build --locked
          #   - cargo test --locked

      - step:
          name: build and deploy to innowise test network
          image: leojonathanoh/docker-kubectl:envsubst-git-jq-kustomize-ssh-v1.14.4
          deployment: dev
          script:
            - echo "$ENV"
            - echo "$PRJNAME"
            - ssh ${USERNAME}@${HOST1} "cd /vitreus/${PRJNAME} && git pull && git checkout ${ENV} && git log | head"
            - ssh ${USERNAME}@${HOST1} "cd /vitreus/${PRJNAME} && docker compose down || true && docker compose up -d --build"
