pipelines:
  branches:   
    dev:
      - step:
          name: Build and Run Tests
          deployment: dev
          image: rustlang/rust:nightly
          caches:
            - cargo
          script:
            - rustup target add wasm32-unknown-unknown
            - apt-get update && apt-get install -y cmake build-essential clang libclang-dev protobuf-compiler

            - cargo fmt -- --check
            - rustup component add clippy
            - cargo clippy -- -D warnings
            - cargo build --release
            - cargo test
