image: rust:1.70
clone:
  depth: full 

pipelines:
  branches:   
    develop:
      - step:
          name: Build and Run Tests
          script:
            - rustup target add wasm32-unknown-unknown
            - export RUSTFLAGS="-C strip=debuginfo"
            - apt-get update && apt-get install -y cmake build-essential clang libclang-dev protobuf-compiler pkg-config libssl-dev libpq-dev gcc llvm jq 
            - cargo fmt -- --check
            - cargo clippy -- -D warnings
            - cargo build --locked
            - cargo test --locked
