image: rust:1.70
clone:
  depth: full 

pipelines:
  branches:   
    develop:
      # - step:
      #     name: Build and Run Tests
      #     script:
      #       - rustup target add wasm32-unknown-unknown
      #       - export RUSTFLAGS="-C strip=debuginfo"
      #       - apt-get update && apt-get install -y cmake build-essential clang libclang-dev protobuf-compiler pkg-config libssl-dev libpq-dev gcc llvm jq 
      #       - cargo fmt -- --check
      #       - cargo clippy -- -D warnings
      #       - cargo build --locked
      #       - cargo test --locked

      - parallel:
          steps:
            - step:
                name: build and deploy to innowise test network instance1
                image: leojonathanoh/docker-kubectl:envsubst-git-jq-kustomize-ssh-v1.14.4
                deployment: dev
                script:
                  - ssh ${USERNAME}@${HOST1} "cd /vitreus/${PRJNAME} && git pull && git checkout ${ENV} && git log | head"
                  - ssh ${USERNAME}@${HOST1} "cd /vitreus/${PRJNAME} && docker compose -f compose.yml down || true && docker system prune -a -f && docker compose -f compose.yml up -d --build"
            
            - step:
                name: build and deploy to innowise test network instance2
                image: leojonathanoh/docker-kubectl:envsubst-git-jq-kustomize-ssh-v1.14.4
                deployment: dev2
                script:
                  - ssh ${USERNAME}@${HOST2} "cd /vitreus/${PRJNAME} && git pull && git checkout ${ENV} && git log | head"
                  - ssh ${USERNAME}@${HOST2} "cd /vitreus/${PRJNAME} && docker compose -f compose2.yml down || true && docker system prune -a -f && docker compose -f compose2.yml up -d --build"

            - step:
                name: build and deploy to innowise test network instance3
                image: leojonathanoh/docker-kubectl:envsubst-git-jq-kustomize-ssh-v1.14.4
                deployment: dev3
                script:
                  - ssh ${USERNAME}@${HOST3} "cd /vitreus/${PRJNAME} && git pull && git checkout ${ENV} && git log | head"
                  - ssh ${USERNAME}@${HOST3} "cd /vitreus/${PRJNAME} && docker compose -f compose3.yml down || true && docker system prune -a -f && docker compose -f compose3.yml up -d --build"