image: rust:1.70
clone:
  depth: full 

pipelines:
  branches:   
    develop:
      - step:
          name: Build and Run Tests
          script:
            - rustup target add wasm32-unknown-unknown
            - apt-get update && apt-get install -y cmake build-essential clang libclang-dev protobuf-compiler

            - cargo fmt -- --check
            - rustup component add clippy rustfmt rust-analyzer
            - cargo clippy -- -D warnings
            - cargo build --locked --all-targets
            - cargo test --locked --all
