[workspace]
members = ["node", "runtime"]
resolver = "2"

[workspace.package]
authors = ["Innowise FinTech Team"]
edition = "2021"
repository = "https://bitbucket.org/innowise-group/vitreus-power-plant"

[workspace.dependencies]
bn = { package = "substrate-bn", version = "0.6", default-features = false }
environmental = { version = "1.1.4", default-features = false }
ethereum = { version = "0.14.0", default-features = false }
ethereum-types = { version = "0.14.1", default-features = false }
evm = { version = "0.39.0", default-features = false }
hex-literal = { version = "0.3.4" }
impl-serde = { version = "0.4.0", default-features = false }
jsonrpsee = "0.16.2"
kvdb-rocksdb = "0.17.0"
libsecp256k1 = { version = "0.7.1", default-features = false }
log = { version = "0.4.17", default-features = false }
parity-db = "0.4.6"
rlp = { version = "0.5", default-features = false }
scale-codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2.3.1", default-features = false, features = [
    "derive",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = "0.7.0-alpha.3"

sc-basic-authorship = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-cli = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-client-api = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-client-db = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-consensus = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-executor = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-keystore = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-network-common = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-network-sync = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-rpc = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-service = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sc-utils = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
# Substrate Primitive
sp-api = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sp-consensus = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-consensus-grandpa = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-database = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sp-inherents = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
sp-offchain = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-state-machine = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-storage = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
# Substrate FRAME
frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-aura = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740", default-features = false }
# Substrate Utility
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", rev = "ba87188cce8c0a11c9542d7363cd5ddd46db2740" }
# Frontier Client
fc-cli = { git = "https://github.com/ales-tsurko/frontier" }
fc-consensus = { git = "https://github.com/ales-tsurko/frontier" }
fc-db = { git = "https://github.com/ales-tsurko/frontier" }
fc-mapping-sync = { git = "https://github.com/ales-tsurko/frontier" }
fc-rpc = { git = "https://github.com/ales-tsurko/frontier" }
fc-rpc-core = { git = "https://github.com/ales-tsurko/frontier" }
fc-storage = { git = "https://github.com/ales-tsurko/frontier" }
# Frontier Primitive
fp-account = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-consensus = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-dynamic-fee = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-ethereum = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-evm = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-rpc = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-self-contained = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
fp-storage = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
# Frontier FRAME
pallet-base-fee = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-dynamic-fee = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-ethereum = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-evm = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-evm-chain-id = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-evm-precompile-modexp = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-evm-precompile-sha3fips = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-evm-precompile-simple = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
pallet-evm-test-vector-support = { git = "https://github.com/ales-tsurko/frontier" }
pallet-hotfix-sufficients = { git = "https://github.com/ales-tsurko/frontier", default-features = false }
# Frontier Template
vitreus-power-plant-runtime = { path = "runtime", default-features = false }
# Arkworks
ark-bls12-377 = { version = "0.4.0", default-features = false, features = [
    "curve",
] }
ark-bw6-761 = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.0", default-features = false }
ark-ff = { version = "0.4.0", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
