version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant-network

  first_node:
    image: vitreus_power_plant
    depends_on:
      - vitreus_power_plant
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/bob
      --chain dev
      --bob
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --node-key=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58
      --validator
      --bootnodes /ip4/140.82.46.161/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp


    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9933:9933/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant-network

networks:
  vitreus_power_plant-network:
    name: vitreus_power_plant