version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant-network

  first_node:
    image: vitreus_power_plant
    container_name: power-plant-first-node
    depends_on:
      - vitreus_power_plant
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/alice
      --chain dev
      --alice
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --unsafe-rpc-external
      --node-key c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      --validator
      --prometheus-external
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9933:9933/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant-network

networks:
  vitreus_power_plant-network:
    name: vitreus_power_plant