version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant_network

  first_node:
    image: vitreus_power_plant
    container_name: power-plant-first-node
    depends_on:
      - vitreus_power_plant
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/bob
      --chain dev
      --bob
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --unsafe-rpc-external
      --node-key=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58
      --validator
      --prometheus-external
      --bootnodes /ip4/149.28.56.46/tcp/30333/p2p/12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      --unsafe-ws-external
      --rpc-cors all
      --telemetry-url "ws://telemetry-power-plant-dev.compliq.io:8001/submit/ 0"


    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9933:9933/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant