version: "3.3"

services:
  archive_node_3:
    image: cdivtrs/power-plant:latest
    container_name: power-plant-archive-node-3
    restart: always
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain ./target/release/vitreus-power-plant-mainnet.json
      --name vitreus-archives
      --port 30333
      --rpc-port 9944
      --rpc-external
      --prometheus-external
      --rpc-cors all
      --rpc-max-connections 5000
      --state-pruning archive
      --enable-offchain-indexing true
      -lwarn

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "0.0.0.0:9615:9615/tcp"
    networks:
      - vitreus_power_plant-network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant-network:
    name: vitreus_power_plant