version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant_network

  power_plant_fourth_node:
    image: vitreus_power_plant
    container_name: power-plant-fourth-node
    restart: always
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain mainnet
      --name backbone-node-4
      --port 30333
      --rpc-port 9944
      --rpc-methods=unsafe
      --validator
      --prometheus-external
      --bootnodes /ip4/45.32.187.143/tcp/30333/p2p/12D3KooWBFQSrDskroYuP9CxKDizTomeSc3sC1K9EgmdpeeJzEnS
      --rpc-cors all
      --telemetry-url "wss://telemetry-dev.compliq.io/submit/ 1"
      --beefy

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "127.0.0.1:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
