version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant-network

  archive_node_3:
    image: vitreus_power_plant
    container_name: power-plant-archive-node-3
    restart: always
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain mainnet
      --name mainnet-archive-3
      --port 30333
      --rpc-port 9944
      --rpc-external
      --prometheus-external
      --bootnodes /ip4/45.32.187.143/tcp/30333/p2p/12D3KooWBFQSrDskroYuP9CxKDizTomeSc3sC1K9EgmdpeeJzEnS
      --rpc-cors all
      --rpc-max-connections 5000
      --state-pruning archive
      --telemetry-url "wss://telemetry-dev.compliq.io/submit/ 0"
      -lwarn

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "0.0.0.0:9615:9615/tcp"
    networks:
      - vitreus_power_plant-network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant-network:
    name: vitreus_power_plant