[package]
name = 'vitreus-power-plant-runtime'
publish = false
version = '0.1.0'
authors = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
fp-account = { workspace = true }
fp-evm = { workspace = true }
fp-rpc = { workspace = true }
fp-self-contained = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-executive = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }
num_enum = { workspace = true }
pallet-aura = { workspace = true }
pallet-balances = { workspace = true }
pallet-base-fee = { workspace = true }
pallet-dynamic-fee = { workspace = true }
pallet-ethereum = { workspace = true }
pallet-evm = { workspace = true }
pallet-evm-chain-id = { workspace = true }
pallet-evm-precompile-balances-erc20 = { workspace = true }
pallet-evm-precompile-modexp = { workspace = true }
pallet-evm-precompile-sha3fips = { workspace = true }
pallet-evm-precompile-simple = { workspace = true }
pallet-grandpa = { workspace = true }
pallet-hotfix-sufficients = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
parity-scale-codec = { workspace = true }
precompile-utils = { workspace = true }
scale-info = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ['std', 'with-rocksdb-weights']
runtime-benchmarks = [
    'frame-benchmarking/runtime-benchmarks', 
    'frame-system-benchmarking/runtime-benchmarks', 
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks', 
    'pallet-grandpa/runtime-benchmarks', 
    'pallet-timestamp/runtime-benchmarks', 
    'pallet-ethereum/runtime-benchmarks', 
    'pallet-evm/runtime-benchmarks', 
    'pallet-hotfix-sufficients/runtime-benchmarks'
]
std = [
    'fp-account/std',
    'fp-evm/std',
    'fp-rpc/std',
    'fp-self-contained/std',
    'frame-benchmarking/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system-benchmarking/std',
    'frame-system-rpc-runtime-api/std',
    'frame-system/std',
    'pallet-aura/std',
    'pallet-balances/std',
    'pallet-base-fee/std',
    'pallet-dynamic-fee/std',
    'pallet-ethereum/std',
    'pallet-evm-chain-id/std',
    'pallet-evm-precompile-balances-erc20/std',
    'pallet-evm-precompile-modexp/std',
    'pallet-evm-precompile-sha3fips/std',
    'pallet-evm-precompile-simple/std',
    'pallet-evm/std',
    'pallet-grandpa/std',
    'pallet-hotfix-sufficients/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-transaction-payment/std',
    'parity-scale-codec/std',
    'scale-info/std',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'substrate-wasm-builder',
]
with-paritydb-weights = []
with-rocksdb-weights = []
