[package]
name = "vitreus-runtime-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-support = { workspace = true, default-features = false }
impl-trait-for-tuples = { workspace = true }
pallet-asset-conversion = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-staking = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "sp-runtime/std",
    "pallet-asset-conversion/std",
    "sp-staking/std",
    "sp-std/std",
]
