[package]
name = "pallet-account-nonce-runtime-api"
version = "0.1.0"
authors = ["Innowise FinTech Team"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { workspace = true }
parity-scale-codec = { workspace = true }

[features]
default = ["std"]
std = [
    "sp-api/std",
]
