version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        BUILD_FEATURES: fast-runtime
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant_network

  first_node:
    image: vitreus_power_plant
    container_name: power-plant-first-node
    restart: always
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain testnet
      --name testnet-val1
      --port 30333
      --rpc-port 9944
      --rpc-methods=unsafe
      --node-key c6354babbc4a8c2a5cd2e5fb0e2f6ccdf0adf520cf5e6ba4fa4ccf484c298427
      --validator
      --prometheus-external
      --bootnodes /ip4/45.77.100.209/tcp/30333/p2p/12D3KooWMzJX1C1PSUXmxkHoVbR9uJKuGQgXJZszx8oA73fnacZn
      --rpc-cors all
      --telemetry-url "wss://telemetry-dev.compliq.io/submit/ 1"
      --beefy

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "127.0.0.1:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
