version: "3.3"

services:
  revert:
    image: cdivtrs/power-plant-testnet:latest
    container_name: power-plant-revert
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      revert
      --base-path /tmp/node
      --chain ./target/release/vitreus-power-plant-testnet.json
      1024

volumes:
  node_data:
    external: true

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
