version: "3.3"

services:
  fifth_node:
    image: cdivtrs/power-plant:testnet-latest
    container_name: power-plant-fifth-node
    restart: always
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain ./target/release/vitreus-power-plant-testnet.json
      --name testnet-val5
      --port 30333
      --rpc-port 9944
      --rpc-methods=unsafe
      --validator
      --prometheus-external
      --rpc-cors all
      --sync warp

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "127.0.0.1:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
