version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ..
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant-network

  archive_node:
    image: vitreus_power_plant
    container_name: power-plant-archive-node
    restart: always
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain testnet
      --name testnet-archive-2
      --port 30333
      --rpc-port 9944
      --rpc-external
      --prometheus-external
      --bootnodes /ip4/45.77.100.209/tcp/30333/p2p/12D3KooWMzJX1C1PSUXmxkHoVbR9uJKuGQgXJZszx8oA73fnacZn
      --rpc-cors all
      --state-pruning archive
      --telemetry-url "wss://telemetry-power-plant-dev.compliq.io:8001/submit/ 0"
      -lwarn

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "0.0.0.0:9615:9615/tcp"
    networks:
      - vitreus_power_plant-network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant-network:
    name: vitreus_power_plant