version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        BUILD_FEATURES: fast-runtime
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant_network

  third_node:
    image: vitreus_power_plant
    container_name: power-plant-third-node
    restart: always
    depends_on:
      - vitreus_power_plant
      - ../chain-specs/vitreus-power-plant-testnet.json:/chain-spec.json
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain /chain-spec.json
      --name testnet-val3
      --port 30333
      --rpc-port 9944
      --rpc-methods=unsafe
      --node-key 18c78063e4bba1dc1077ce4013de211f170fa8bbedc3906de373aa7c997b587c
      --validator
      --prometheus-external
      --bootnodes /ip4/45.77.100.209/tcp/30333/p2p/12D3KooWMzJX1C1PSUXmxkHoVbR9uJKuGQgXJZszx8oA73fnacZn
      --rpc-cors all
      --telemetry-url "wss://telemetry-dev.compliq.io/submit/ 1"
      --beefy

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "127.0.0.1:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
