version: "3.3"

services:
  archive_node:
    image: cdivtrs/power-plant-testnet:latest
    container_name: power-plant-archive-node
    restart: always
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain ./target/release/vitreus-power-plant-testnet.json
      --name testnet-archive-2
      --port 30333
      --rpc-port 9944
      --rpc-external
      --rpc-max-connections 5000
      --prometheus-external
      --rpc-cors all
      --state-pruning archive

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "0.0.0.0:9615:9615/tcp"
    networks:
      - vitreus_power_plant-network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant-network:
    name: vitreus_power_plant