version: "3.3"

services:
  vitreus_power_plant:
    build:
      context: ..
      dockerfile: Dockerfile
    image: vitreus_power_plant
    networks:
      - vitreus_power_plant_network

  first_node:
    image: vitreus_power_plant
    container_name: power-plant-first-node
    restart: always
    depends_on:
      - vitreus_power_plant
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/bob
      --chain devnet
      --bob
      --port 30333
      --rpc-port 9944
      --unsafe-rpc-external
      --validator
      --prometheus-external
      --bootnodes /ip4/45.77.147.229/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      --rpc-cors all
      --telemetry-url "wss://telemetry-power-plant-dev.compliq.io:8001/submit/ 5"


    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
