version: "3.3"

services:
  second_node:
    image: cdivtrs/power-plant-testnet:latest
    container_name: power-plant-second-node
    restart: always
    depends_on:
      - vitreus_power_plant
    volumes:
      - node_data:/tmp/node
    command: >
      ./target/release/vitreus-power-plant-node
      --base-path /tmp/node
      --chain ./target/release/vitreus-power-plant-testnet.json
      --name testnet-val2
      --port 30333
      --rpc-port 9944
      --rpc-methods=unsafe
      --node-key 18c78063e4bba1dc1077ce4013de211f170fa8bbedc3906de373aa7c997b587c
      --validator
      --prometheus-external
      --rpc-cors all
      --sync warp

    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "127.0.0.1:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"
    networks:
      - vitreus_power_plant_network

volumes:
  node_data:
    driver: local

networks:
  vitreus_power_plant_network:
    name: vitreus_power_plant
