[package]
name = "energy-broker-rpc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
energy-broker-runtime-api = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
parity-scale-codec = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-rpc = { workspace = true }
sp-runtime = { workspace = true }
